services:
  bind9:
    build: .
    container_name: bind9-container
    environment:
      - TZ=UTC
    ports:
      - "30053:53"
      - "30053:53/udp"
      - "953:953/tcp"
      - "3000:3000"  # Expose the Node.js API port
    volumes:
      - ./bind:/etc/bind
      - ./app:/app