services:
  bind9:
    build: .
    container_name: bind9-container
    environment:
      - TZ=UTC
    ports:
      - "30053:53"
      - "30053:53/udp"
      - "953:953/tcp"
      - "5000:5000"  # Expose the Node.js API port
    volumes:
      - ./config/named.conf.options:/etc/bind/named.conf.options
      - ./config/named.conf.local:/etc/bind/named.conf.local
      - ./zones:/etc/bind/zones